services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_ALLOW_EMPTY_PASSWORD: "YES"
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    
    networks:
      - smart-divide
networks:
  smart-divide:
    external: true
