name: Java 21 • Test
on: [push]
jobs:
    test:
        name: Install & Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Temurin JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: '21'
                cache: maven


            - name: Run tests with maven
              run: mvn clean install test